index:
    path: /
    controller: App\Controller\DefaultController::index

accueil:
    path: /home
    controller: App\Controller\DefaultController::index

personnages:
    path: /personnages
    controller: App\Controller\CharsController::index

pages:
    path: /personnages/p{page}-{limit}
    controller: App\Controller\CharsController::index
    requirements:
        path: ^p[1-9]+-[1-9]{3}$

getChars:
    path: /getChars
    controller: App\Controller\CharsController::getPersonnages

showChars:
    path: /personnages/show/{id}
    controller: App\Controller\CharsController::showPersonnage
    requirements:
        id: \d+

showCharDetails:
    path: /showCharDetails
    controller: App\Controller\CharsController::showPersonnage

pageNotFound:
    path: /{path}
    controller: App\Controller\DefaultController::index
    requirements:
        path: .*